create table PRACOWNICY_WYPOZYCZALNI
(
    IMIE              VARCHAR2(20 char)                                                         not null,
    NAZWISKO          VARCHAR2(20 char)                                                         not null,
    ID_PRAC           NUMBER default "INF141282"."ISEQ$$_198652".nextval generated by default on null as identity
        constraint PRACOWNICY_PK
        primary key,
    DATA_ZATRUDNIENIA DATE   default TO_DATE(TO_CHAR(CURRENT_DATE, 'dd/mm/yyyy'), 'dd/mm/yyyy') not null,
    DATA_ZWOLNIENIA   DATE
)
/