create table ROWERY
(
    ID_ROWERU          NUMBER            default "INF141282"."ISEQ$$_198657".nextval generated by default on null as identity
        constraint ROWERY_PK
        primary key,
    KOLOR              VARCHAR2(10 char)                                                                    not null,
    DATA_ZAKUPU        DATE              default TO_DATE(TO_CHAR(CURRENT_DATE, 'dd/mm/yyyy'), 'dd/mm/yyyy') not null,
    MODEL_ROWERU_NAZWA VARCHAR2(20 char)                                                                    not null
        constraint ROWERY_MODEL_ROWERU_FK
            references MODELE_ROWEROW,
    STATUS             VARCHAR2(20 char) default 'wolny'                                                    not null
        constraint CHK_ROWERY_STATUS
            check (status IN ('wypożyczony', 'wolny', 'brak', 'uszkodzony'))
)
/

create index ROWERY_STATUS_NAZWA
    on ROWERY (STATUS, MODEL_ROWERU_NAZWA)
/

