create table WYPOZYCZENIA
(
    DATA_WYPOZYCZENIA DATE   default TO_DATE(TO_CHAR(CURRENT_DATE, 'dd/mm/yyyy'), 'dd/mm/yyyy') not null,
    DATA_ZWROTU       DATE,
    KLIENT_NR_DOWODU  VARCHAR2(10 char)                                                         not null
        constraint WYPOZYCZENIA_KLIENT_FK
            references KLIENCI,
    ID_PRAC           NUMBER                                                                    not null
        constraint WYPOZYCZENIA_PRACOWNIK_FK
            references PRACOWNICY_WYPOZYCZALNI,
    ID_ROWERU         NUMBER                                                                    not null
        constraint WYPOZYCZENIA_ROWER_FK
            references ROWERY,
    ID_AKCESORIUM     NUMBER
        constraint WYPOZYCZENIA_AKCESORIUM_FK
            references AKCESORIA,
    ID_WYPOZYCZENIA   NUMBER default "INF141282"."ISEQ$$_198665".nextval generated by default on null as identity
        constraint WYPOZYCZENIA_PK
        primary key,
    constraint CHK_WYPOZYCZENIA_DATY
        check (data_zwrotu IS NULL OR data_zwrotu >= data_wypozyczenia)
)
/

